dep: auth-servic

diff --git a/.github/workflows/auth-cicd.yml b/.github/workflows/auth-cicd.yml
--- a/.github/workflows/auth-cicd.yml
+++ b/.github/workflows/auth-cicd.yml
@@ -1,150 +1,146 @@
-# name: CI/CD API Gateway
+name: CI/CD Auth Sevice
 
-# on:
-#   push:
-#     branches:
-#       - main
-#     paths:
-#       - "packages/api-gateway/**"
+on:
+  push:
+    branches:
+      - main
+    paths:
+      - "packages/auth/**"
 
-# defaults:
-#   run:
-#     working-directory: packages/api-gateway
+defaults:
+  run:
+    working-directory: packages/auth
 
-# jobs:
-#   build:
-#     runs-on: ubuntu-latest
+jobs:
+  build:
+    runs-on: ubuntu-latest
 
-#     steps:
-#       - uses: actions/checkout@v4
+    steps:
+      - uses: actions/checkout@v4
 
-#       - name: Set up Node.js
-#         uses: actions/setup-node@v4
-#         with:
-#           node-version: "20"
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
 
-#       - name: Install dependencies
-#         run: yarn install
+      - name: Install dependencies
+        run: yarn install
 
-#       - name: Build the project
-#         run: yarn build
+      - name: Build the project
+        run: yarn build
 
-#       - name: Archive Production Artifact
-#         uses: actions/upload-artifact@v2
-#         with:
-#           name: build
-#           path: packages/api-gateway/build
+      - name: Archive Production Artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: build
+          path: packages/auth/build
 
-#   deploy:
-#     needs: build
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Get the Production Artifact
-#         uses: actions/download-artifact@v2
-#         with:
-#           name: build
-#           path: packages/api-gateway/build
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Get the Production Artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: build
+          path: packages/auth/build
 
-#       - name: Add SSH Key
-#         uses: webfactory/ssh-agent@v0.5.3
-#         with:
-#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+      - name: Add SSH Key
+        uses: webfactory/ssh-agent@v0.5.3
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-#       - name: Add Known Hosts
-#         run: ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
+      - name: Add Known Hosts
+        run: ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
 
-#       - name: Ensure target directory exists
-#         uses: appleboy/ssh-action@master
-#         with:
-#           host: ${{ secrets.EC2_IP }}
-#           username: ${{ secrets.EC2_USERNAME }}
-#           key: ${{ secrets.SSH_PRIVATE_KEY }}
-#           port: 22
-#           script: |
-#             mkdir -p /home/ubuntu/apps
-#             chown ubuntu:ubuntu /home/ubuntu/apps
+      - name: Ensure target directory exists
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            mkdir -p /home/ubuntu/apps
+            chown ubuntu:ubuntu /home/ubuntu/apps
 
-#       - name: Copy files to EC2
-#         uses: appleboy/scp-action@master
-#         with:
-#           host: ${{ secrets.EC2_IP }}
-#           username: ${{ secrets.EC2_USERNAME }}
-#           key: ${{ secrets.SSH_PRIVATE_KEY }}
-#           port: 22
-#           source: "packages/api-gateway/build/*"
-#           target: "/home/ubuntu/apps/"
+      - name: Copy files to EC2
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          source: "packages/auth/build/*"
+          target: "/home/ubuntu/apps/"
 
-#       - name: Create .env file
-#         uses: appleboy/ssh-action@master
-#         with:
-#           host: ${{ secrets.EC2_IP }}
-#           username: ${{ secrets.EC2_USERNAME }}
-#           key: ${{ secrets.SSH_PRIVATE_KEY }}
-#           port: 22
-#           script: |
-#             sudo mkdir -p /home/***/apps/api-gateway/build/configs
-#             sudo chown -R $USER:$USER /home/***/apps
-#             cat <<EOF > /home/***/apps/api-gateway/build/configs/.env.prod
-#             NODE_ENV=${{ secrets.NODE_ENV }}
-#             PORT=${{ secrets.PORT }}
-#             COOKIE_SECRET_KEY_ONE=${{ secrets.COOKIE_SECRET_KEY_ONE }}
-#             COOKIE_SECRET_KEY_TWO=${{ secrets.COOKIE_SECRET_KEY_TWO }}
-#             COOKIE_PERSISTENT_KEY=${{ secrets.COOKIE_PERSISTENT_KEY }}
-#             CLIENT_URL=${{ secrets.CLIENT_URL }}
-#             LOG_LEVEL=${{ secrets.LOG_LEVEL }}
-#             RABBITMQ_ENDPOINT=${{ secrets.RABBITMQ_ENDPOINT }}
-#             USER_SERVICE_URL=${{ secrets.USER_SERVICE_URL }}
-#             AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL }}
-#             TEACHER_SERVICE_URL=${{ secrets.TEACHER_SERVICE_URL }}
-#             NOTIFICATION_SERVICE_URL=${{ secrets.NOTIFICATION_SERVICE_URL }}
-#             STUDENT_SERVICE_URL=${{ secrets.STUDENT_SERVICE_URL }}
-#             TEST=${{ secrets.TEST }}
-#             EOF
-#       - name: Start
-#         uses: appleboy/ssh-action@master
-#         with:
-#           host: ${{ secrets.EC2_IP }}
-#           username: ${{ secrets.EC2_USERNAME }}
-#           key: ${{ secrets.SSH_PRIVATE_KEY }}
-#           port: 22
-#           script: |
-#             #!/bin/bash
+      - name: Create .env file
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            sudo mkdir -p /home/***/apps/auth/build/configs
+            sudo chown -R $USER:$USER /home/***/apps
+            cat <<EOF > /home/***/apps/auth/build/configs/.env.prod
+            NODE_ENV=${{ secrets.NODE_ENV }}
+            PORT=${{ secrets.PORT }}
+            CLIENT_URL=${{ secrets.CLIENT_URL }}
+            LOG_LEVEL=${{ secrets.LOG_LEVEL }}
+            RABBITMQ_ENDPOINT=${{ secrets.RABBITMQ_ENDPOINT }}
+            USER_SERVICE_URL=${{ secrets.USER_SERVICE_URL }}
+            TEACHER_SERVICE_URL=${{ secrets.TEACHER_SERVICE_URL }}
+            STUDENT_SERVICE_URL=${{ secrets.STUDENT_SERVICE_URL }}
+            MONGODB_URL=${{ secrets.MONGODB_URL}}
+            TEST=${{ secrets.TEST }}
+            EOF
+      - name: Start
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            #!/bin/bash
 
-#             # Check if nvm is installed
-#             if [ -s "$HOME/.nvm/nvm.sh" ]; then
-#               source "$HOME/.nvm/nvm.sh"
-#             elif [ -s "/usr/local/nvm/nvm.sh" ]; then
-#               source "/usr/local/nvm/nvm.sh"
-#             else
-#               echo "nvm is not installed."
-#               exit 1
-#             fi
+            # Check if nvm is installed
+            if [ -s "$HOME/.nvm/nvm.sh" ]; then
+              source "$HOME/.nvm/nvm.sh"
+            elif [ -s "/usr/local/nvm/nvm.sh" ]; then
+              source "/usr/local/nvm/nvm.sh"
+            else
+              echo "nvm is not installed."
+              exit 1
+            fi
 
-#             # Verify yarn installation
-#             if ! command -v yarn &> /dev/null; then
-#               echo "Yarn could not be found"
-#               exit 1
-#             fi
+            # Verify yarn installation
+            if ! command -v yarn &> /dev/null; then
+              echo "Yarn could not be found"
+              exit 1
+            fi
 
-#             cd /home/ubuntu/apps/packages/api-gateway/build
-#             echo "Checking directory contents..."
-#             ls -alh # Lists all files in the current directory
+            cd /home/ubuntu/apps/packages/auth/build
+            echo "Checking directory contents..."
+            ls -alh # Lists all files in the current directory
 
-#             # Check if server.js exists in the correct directory
-#             if [ ! -f ./src/server.js ]; then
-#               echo "server.js not found in ./src/"
-#               exit 1
-#             fi
+            # Check if server.js exists in the correct directory
+            if [ ! -f ./src/server.js ]; then
+              echo "server.js not found in ./src/"
+              exit 1
+            fi
 
-#             # Install Dependencies
-#             echo "Installing dependencies..."
-#             yarn install
+            # Install Dependencies
+            echo "Installing dependencies..."
+            yarn install
 
-#             # Check if the PM2 process is running
-#             if pm2 show api-gateway > /dev/null; then
-#               echo "Application is running. Restarting..."
-#               restart api-gateway
-#             else
-#               echo "Application is not running. Starting..."
-#               yarn start
-#             fi
+            # Check if the PM2 process is running
+            if pm2 show auth > /dev/null; then
+              echo "Application is running. Restarting..."
+              restart auth
+            else
+              echo "Application is not running. Starting..."
+              yarn start
+            fi
